/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "GoogleMapsApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Media": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NextAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}